name: Style Dictionary Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Validate JSON syntax
      run: |
        for file in tokens/*.json; do
          echo "Validating $file"
          cat "$file" | jq empty
        done

    - name: Convert JSON and build CSS
      run: node build.mjs

    - name: Lint CSS file
      run: npx stylelint "dist/theme/*.css"
