name: Lint, Build, and Check CSS

on: [push, pull_request]
permissions:
  contents: write
jobs:
  lint-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Check JSON syntax
        run: |
          for file in tokens/*.json; do
            echo "Checking $file"
            cat "$file" | jq empty
          done

      - name: Build CSS from JSON tokens
        run: node build.mjs

      - name: List dist/theme directory
        run: ls -la dist/theme

      - name: Run Stylelint
        run: npx stylelint 'dist/theme/*.css' --fix

      - name: Check for changes
        id: git-status
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff-index --quiet HEAD; then
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git commit -m 'Apply Stylelint fixes'
          git push https://${{ secrets.GH_TOKEN }}@github.com/Valmire-Nivokazi/Thesis_FR_SS2024.git HEAD:main

      - name: Upload CSS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: css-artifacts
          path: dist/theme/design.token.css

      - name: Download previous CSS artifact
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: css-artifacts
          path: .

      - name: Rename previous CSS file
        if: always()
        run: |
          if [ -f ./design.token.css ]; then
            mv ./design.token.css old_design.token.css
          fi

      - name: Check if current CSS exists
        run: |
          if [ ! -f dist/theme/design.token.css ]; then
            echo "Current CSS file not found!"
            exit 1
          fi

      - name: Categorize Changes
        run: node categorize_changes.cjs dist/theme/design.token.css old_design.token.css categorized_changes.txt

      - name: Upload Change Report
        uses: actions/upload-artifact@v2
        with:
          name: categorized-changes-report
          path: categorized_changes.txt

      - name: Save current CSS for next run
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: css-artifacts
          path: dist/theme/design.token.css
