name: Lint, Build, and Check JSON Tokens

on:
  pull_request:
    branches:
      - main
    paths:
      - 'tokens/**'

permissions:
  contents: write

jobs:
  lint-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Check JSON syntax
        run: |
          for file in tokens/*.json; do
            echo "Checking $file"
            cat "$file" | jq empty
          done

      - name: Build CSS from JSON tokens
        run: node build.mjs

      - name: List dist/theme directory
        run: ls -la dist/theme

      - name: Run Stylelint
        run: npx stylelint 'dist/theme/*.css' --fix

      - name: Generate code diff
        run: |
          echo "old_tokens_dir: old_tokens" > code_diff.txt
          git diff HEAD~1 HEAD >> code_diff.txt

      - name: Print code_diff.txt for debugging
        run: cat code_diff.txt

      - name: Categorize JSON changes
        run: node categorize_json_changes.cjs tokens old_tokens categorized_changes.txt

      - name: Commit and push changes
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Apply Stylelint fixes'
          git pull origin $BRANCH_NAME --rebase || git rebase --abort
          git push origin HEAD:$BRANCH_NAME

      - name: Cleanup old tokens directory
        run: |
          rm -rf old_tokens
          mkdir old_tokens
          git checkout HEAD~1 -- tokens/
          cp -r tokens/* old_tokens/

      - name: Upload categorized changes
        uses: actions/upload-artifact@v2
        with:
          name: categorized-changes
          path: categorized_changes.txt
