name: Code Diff Analysis

on: [push, pull_request]
permissions:
  contents: write
jobs:
  code-diff-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Generate Code Diff
        id: generate_diff
        run: git diff HEAD~1 HEAD > code_diff.txt

      - name: List changed files
        id: list_changed_files
        run: git diff --name-only HEAD~1 HEAD > changed_files.txt

      - name: Upload Code Diff
        uses: actions/upload-artifact@v2
        with:
          name: code-diff
          path: code_diff.txt

      - name: Upload Changed Files List
        uses: actions/upload-artifact@v2
        with:
          name: changed-files
          path: changed_files.txt

      - name: Print changed files
        run: cat changed_files.txt
