name: Lint, Build, Check, and Diff

on: [push, pull_request]

jobs:
  lint-build-check-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Check JSON syntax
        run: |
          for file in tokens/*.json; do
            echo "Checking $file"
            cat "$file" | jq empty
          done

      - name: Build CSS from JSON tokens
        run: node build.mjs

      - name: Run Stylelint
        run: npx stylelint 'dist/theme/*.css' --fix

      - name: Check for changes
        id: git-status
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || echo "has_changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git commit -m 'Apply Stylelint fixes'
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Generate diff
        if: env.has_changes == 'true'
        run: |
          git diff HEAD^ > code_diff.txt

      - name: Upload diff report
        if: env.has_changes == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: code-diff
          path: code_diff.txt
