name: Lint, Build, and Check CSS

on: [push, pull_request]
permissions:
  contents: write
jobs:
  lint-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Check JSON syntax
        run: |
          for file in tokens/*.json; do
            echo "Checking $file"
            cat "$file" | jq empty
          done

      - name: Build CSS from JSON tokens
        run: node build.mjs

      - name: List dist/theme directory
        run: ls -la dist/theme

      - name: Run Stylelint
        run: npx stylelint 'dist/theme/*.css' --fix

      - name: Generate Git Diff
        id: git-diff
        run: |
          if [ $(git rev-parse --is-shallow-repository) ]; then
            git fetch --unshallow
          fi
          if [ $(git rev-parse HEAD^) ]; then
            git diff HEAD^ HEAD > code_diff.txt
          else
            echo "First commit, no previous commit to compare." > code_diff.txt
          fi

      - name: Check for changes
        id: git-status
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff-index --quiet HEAD; then
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git commit -m 'Apply Stylelint fixes'
          git push https://${{ secrets.GH_TOKEN }}@github.com/Valmire-Nivokazi/Thesis_FR_SS2024.git HEAD:main

      - name: Categorize CSS Changes
        if: steps.git-diff.outputs.has_changes == 'true'
        run: node categorize_changes.cjs dist/theme/design.token.css old_design.token.css categorized_changes.txt

      - name: Upload CSS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: css-artifacts
          path: dist/theme/*.css

      - name: Upload diff and categorized changes
        uses: actions/upload-artifact@v2
        with:
          name: diff-and-categorized-changes
          path: |
            code_diff.txt
            categorized_changes.txt
