name: Design Tokens Pipeline

on: [push, pull_request]

jobs:
  json_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate JSON Syntax
        run: jq empty tokens.json

  convert_to_css:
    runs-on: ubuntu-latest
    needs: json_lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Convert JSON to CSS
        run: npm run build

      - name: Verify CSS creation
        run: |
          if [ ! -f dist/tokens.css ]; then
            echo "CSS file not created!"
            exit 1
          else
            echo "CSS file created successfully"
          fi

      - name: Display CSS content
        run: cat dist/tokens.css

  css_lint:
    runs-on: ubuntu-latest
    needs: convert_to_css
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Lint CSS
        run: npx stylelint "dist/tokens.css"